[package]
name = "chip8"
version = "0.1.0"
authors = ["aleks-workpc <alek@sokanu.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
sdl2 = "0.32"

[features]
default = []
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]
